### ISSUE TITLE
No messages

### ISSUE THREAD

**Issue by 3skr0** [bitsofinfo/logstash-modsecurity#11]
Hi,
I have this as log being send by log stash:

>2015-04-24T11:43:30.000+0000 hostname.eu %{message} 
>2015-04-24T11:43:55.000+0000 hostname.eu %{message}

**Comment by bitsofinfo** [comment]
I don't understand your question

**Comment by 3skr0** [comment]
launching :
> /opt/logstash/bin/logstash -f /etc/logstash/conf.d/logstash-modsecurity.conf  

give me 

> 2015-04-24T11:43:30.000+0000 hostname.eu %{message} 
> 2015-04-24T11:43:55.000+0000 hostname.eu %{message}

**Comment by bitsofinfo** [comment]
What does your customized `/etc/logstash/conf.d/logstash-modsecurity.conf` actually look like?

Also please post some sample events from your modsec audit log file, that your config is actually reading from.

**Comment by 3skr0** [comment]
I have just changed the path of my modsec_audit.log file.

and


 >--b9777e35-A--
[24/Apr/2015:19:34:17 +0200] AcAcAcXtAcAcdcAOnc4cAcAc 80.119.145.66 56927 127.0.0.1 80
--b9777e35-B--
GET /fr/test/?a=1'%20or%202 HTTP/1.1
Host: hostname.eu
DNT: 1
Cookie: allpub_2_123=1; customID=4m31mahbrvhcv6v1chmbtqr0c5; PHPSESSID=4m31mahbrvhcv6v1chmbtqr0c5; __utma=164241391.113747390.1407409622.1429880833.1429896156.50; __utmb=164241391.1.10.1429896156; __utmc=164241391; __utmz=164241391.1407411177.2.2.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/9.0.5 Safari/700.8.19
Accept-Language: fr-fr
Accept-Encoding: gzip, deflate
Cache-Control: max-age=0

>--b9777e35-F--
HTTP/1.1 200 OK
Set-Cookie: allpub_2_121=1; expires=Fri, 24-Apr-2015 19:34:17 GMT; path=/; domain=hostname.eu
Set-Cookie: allpub_2_123=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=hostname.eu
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-XSS-Protection: 1; mode=block
X-Frame-Options: sameorigin
Server: 
Content-Type: text/html; charset=utf-8
Content-Length: 55204
Connection: keep-alive

>--b9777e35-E--

>--b9777e35-H--
Message: Warning. Pattern match "(?i:\\bor\\b ?(?:\\d{1,10}|[\\'\"][^=]{1,10}[\\'\"]) ?[=<>]+|(?i:'\\s+x?or\\s+.{1,20}[+\\-!<>=])|\\b(?i:x?or)\\b\\s+(\\d{1,10}|'[^=]{1,10}')|\\b(?i:x?or)\\b\\s+(\\d{1,10}|'[^=]{1,10}')\\s*?[=<>])" at ARGS:a. [file "/etc/modsecurity/owasp-modsecurity-crs/activated_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "133"] [id "959071"] [rev "2"] [msg "SQL Injection Attack"] [data "Matched Data: or 2 found within ARGS:a: 1' or 2"] [severity "CRITICAL"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "8"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [tag "WASCTC/WASC-19"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/CIE1"] [tag "PCI/6.5.2"]
Message: Warning. Pattern match "(?i:(?:[\"'`\xc2\xb4\xe2\x80\x99\xe2\x80\x98]\\s*?(x?or|div|like|between|and)\\s*?[\"'`\xc2\xb4\xe2\x80\x99\xe2\x80\x98]?\\d)|(?:\\\\x(?:23|27|3d))|(?:^.?[\"'`\xc2\xb4\xe2\x80\x99\xe2\x80\x98]$)|(?:(?:^[\"'`\xc2\xb4\xe2\x80\x99\xe2\x80\x98\\\\]*?(?:[\\ ..." at ARGS:a. [file "/etc/modsecurity/owasp-modsecurity-crs/activated_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "237"] [id "981242"] [msg "Detects classic SQL injection probings 1/2"] [data "Matched Data: ' or 2 found within ARGS:a: 1' or 2"] [severity "CRITICAL"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"]
Apache-Handler: IIS
Stopwatch: 1429896852000796 5412702 (- - -)
Stopwatch2: 1429896852000796 5412702; combined=2333, p1=197, p2=2034, p3=2, p4=66, p5=34, sr=50, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for nginx (STABLE)/2.8.0 (http://www.modsecurity.org/); OWASP_CRS/2.2.9.
Server: ModSecurity Standalone
Engine-Mode: "DETECTION_ONLY"

>--b9777e35-Z--
