### ISSUE TITLE
Modularize logstash-modsecurity config

### ISSUE THREAD

**Issue by breml** [bitsofinfo/logstash-modsecurity#18]
We did some tests with your modsecurity configuration for logstash and we really *like it*. Thank you!
Now we want to move a step forward and use this configuration in production. One problem we are facing is the following:

We have to apply some changes to the provided configuration, for example we want to remove the optional parts like "X-Forwarded-For" and "Cookie" and we plan to add some additional filters. At the same time we would love to stay compatible to the upstream configuration provided in this git repository. Therefore I would like to suggest a modularization of the provided configuration.

Before putting actual work into this proposal, I would like to know what you are thinking about this idea.

My suggestion is the following:

Logstash does allow to load the configuration from a directory, where the files are concatenated in lexicographical order.
If the logstash-modsecurity configuration is modularized into several files, it would become easy to select those parts, we want to use and omit the others, like cherry-picking.
This allows to have the logstash-modsecurity repository for example in /etc/logstash/logstash/modsecurty and then simply make symlinks to /etc/logstash/config.d where our logstash installation will look for the actual configuration.
To preserve the correct order, the modularized config parts and the respective symlinks could be prefixed with a number.

E. g. 
* 001_input_file.conf
* 100_filter_split_sections.conf
* 110_filter_section_a.conf
* 120_filter_section_b.conf

Every part of the filter should be placed in a separate file an be surrounded by `filter { ... }`. 

This way we are free select the filters we want to use from logstash-modsecurity and to insert own filters between and after the existing ones.

**Comment by bitsofinfo** [comment]
Sounds great, go ahead and create a PR for your suggested changes. The only thing I would ask is

a) coordinate with this PR https://github.com/bitsofinfo/logstash-modsecurity/pull/12 (as I like the formatting he did over the original hard to read one-liners).

b) Do some testing on 1.4.x and 1.5x, and 2.x line of logstash. Need to get a baseline for if the latest master would be compatible across versions or we create a new 1.5.x+ only version (as the trunk sort of is at this point)

thanks for the interest and ideas

**Comment by breml** [comment]
In our installation we use 1.4.x and 1.5.x, so yes I will test with those.

PR #12 does include much more than the formatting of the inline ruby code, especially some of the regex / grok patterns are changed and I can't estimate the impact. So my proposal is, to do the inline ruby formatting in a separate PR and afterwards begin with the modularization.

**Comment by bitsofinfo** [comment]
@MWilkinson can you please chime in? I think we need to coordinate your #12 pr and what @breml is suggesting.

**Comment by MWilkinson** [comment]
Hi @bitsofinfo and @breml ,

This sounds like a great idea to me, especally as it follows in the tradition of configuring modsecurity itself. I've updated the PR now.
I'd suggest wraping each section (sub-file) with a 'if [type] == "mod_security" { }' just in case people have additional logfiles being filtered. @breml  this would fit inside your 'filter { }'

Some of the re-organisation in my PR should help with splitting into seperate files... 
Would like to see the 'extra' processing in seperate files from the rawsection processing...ie, the processing of [requestHeaders][Cookies] or [responseHeaders]

**Comment by breml** [comment]
@bitsofinfo and @MWilkinson 

I have updated #22 with the condition 'if [type] == "mod_security" { }'

the processing of Cookies and responseHeaders are already in separate files.

**Comment by bitsofinfo** [comment]
Appreciate the contributions, to get this merging along I created a 1.1 release (pre-PRs) and just merged in @MWilkinson's PR. So now from here @breml lets get your PR adjusted for the trunk and I'll merge them in.

**Comment by breml** [comment]
I have updated #22 to represent the changes of @MWilkinson . Hopefully I caught all of them.
Now there is only one place left, where patterns_dir is used. It would be nice to eliminate this one as well as the whole config would become much more portable.

**Comment by bitsofinfo** [comment]
Merged both, awesome guys. Lets all do some testing now

**Comment by bitsofinfo** [comment]
Agree, please eliminate the patterns dir, that is something I did a long while back, and never got rid of it. That pattern can just be moved to it directly inline.

**Comment by bitsofinfo** [comment]
We should also update the README (if warrented) for any helpful, updated info about how things work, deployment tips etc for this new layout

**Comment by MWilkinson** [comment]
I haven't had time to test this, but if we update the 'rawSectionA' grok
pattern to

grok {
  match => {
    "rawSectionA} =>
"\[(?<modsec_timestamp>[0-9]{2}/[A-Za-z]{3,4}/[0-9]{4}:[0-9]{2}:[0-9]{2}:[0-9]{2}
[-\+]{1,2}[0-9]{1,4}) %{DATA:uniqueId} %{IP:sourceIp} %{INT:sourcePort}
%{IP:destIp} %{INT:destPort}"
  }
}

We should be able to do away with that patterns_dir part of the filter.

Regards
Mark

**Comment by bitsofinfo** [comment]
yeah should just be a straight copy paste of the pattern into the inline expression

**Comment by MWilkinson** [comment]
to capture it all as one variable, just need to expand all the patterns and
enclose in a (?<variable>...) construct..

so... (?<modsec_timestamp>%{MONTHDAY}/%{MONTH}/%{YEAR}:%{TIME}
[-\+]{1,2}%{INT})

should work in place of %{L1_TIMESTAMP:modsec_timestamp}  as well

**Comment by bitsofinfo** [comment]
great, please go ahead and submit a PR whenever for what is additionally needed

**Comment by MWilkinson** [comment]
ok, PR #23 created to remove the pattern file and replace with above suggestion

**Comment by bitsofinfo** [comment]
Guys, @see https://github.com/bitsofinfo/logstash-modsecurity/issues/24

**Comment by bitsofinfo** [comment]
Also the README file needs an overhaul now with some instructions after this major refactor. Can anyone contribute that?

**Comment by breml** [comment]
I know, the README needs some love (may be a native english speaker could take this part) and I would like to provide a small shell-script to give an example how to setup the symlinks, but I was busy the last few days.

**Comment by bitsofinfo** [comment]
I can tweak whatever you come up with after a initial stab at an updated README.

Was also thinking we add a script that would take all the *.conf files detected, and merge them into one file (for folks who just prefer a single conf they could generate and then tweak) (like the older versions)

**Comment by saknopper** [comment]
Is it really necessary to create a script to merge the config files? You could just mention in the README to run
```
cat *.conf > [OUTPUTFILE]
```
for example.

**Comment by bitsofinfo** [comment]
Good enough!

**Comment by breml** [comment]
OK, for a start `cat *.conf > [OUTPUTFILE]` is enough, but this does not explain, why the config was modularized in the first place.

The main reason for the modularization was, to provide the possibility to cherry pick those parts of the configuration one would like to use, while still stay compatible to the upstream project. For a real deployment my suggestion is to use symlinks instead of concatenate all existing parts of the configuration to one file together.
Using symlinks provides the possibility to insert own parts for the configuration, for example handling of some headers, only relevant in the respective use case.

So what I have in mind is a small scripts, which creates/maintains the symlinks for those parts of the configuration, the user has selected in a configfile (/etc/logstash-modsecurity.conf).

In this configfile the user defines:
* Path, where the final logstash config resides (e.g. /etc/logstash/conf.d)
* Path, where the logstash-modsecurity git checkout resides (e.g. /opt/logstash-modsecurity)
* How the logstash-modsecurity config parts should be deployed (symlink or concat)
* Which parts of the logstash-modsecurity should be taken in account

**Comment by breml** [comment]
@bitsofinfo what do you think, is this issue resolved?

**Comment by bitsofinfo** [comment]
Mainly yes, however I still have not had time to even personally run it post-refactor. Need to verify it all on ls 1.4.x, 1.5.x and 2.x lines; tweak the README more etc.

**Comment by bitsofinfo** [comment]
Guys could really use some updated docs for README for utilizing this new refactored format you contributed

**Comment by breml** [comment]
I provided an update to the README.md in my last commit. What is missing?
