### ISSUE TITLE
Configuration parse error

### ISSUE THREAD

**Issue by saknopper** [bitsofinfo/logstash-modsecurity#24]
When performing a config test on a fresh checkout of the master branch, I'm getting the following error:

```
./logstash -t -f modsec_conf/0000_header.conf 
Error: Expected one of #, input, filter, output at line 40, column 1 (byte 1515) after ##########################################################
```
I'm only parsing the header now since I was trying to determine the location of the error and it turns out to be the header...

Am I the only one with this issue?

Using logstash 1.5.5

**Comment by bitsofinfo** [comment]
@MWilkinson  and @breml  should chime in, there were recently some major refactoring changes that were merged in a PR, sounds like one of those filter files is syntactically incorrect. 

Until fixed, please use one of the versions under "releases"

**Comment by MWilkinson** [comment]
Hi @saknopper, can you please list which of the split files you have configured or which you have (if any) removed ?

Also the details of any custom filter files you may have added. 

Regards

**Comment by bitsofinfo** [comment]
This is likely due to the file `0000_header.conf` .. as line 39 is the last line and this file does not include ANY actual `filter {}` block....

**Comment by bitsofinfo** [comment]
@saknopper try removing `0000_header.conf`

**Comment by breml** [comment]
The single configuration files of the modularized configuration are not intended to be used alone but to give the user the freedom to cherry-pick those parts he want's to use. In our case, the elements of the logstash-modsecurity configuration is only a part of our configuration.

It's in the users responsibility to build a valid logstash configuration.

**Comment by bitsofinfo** [comment]
We just need to include this kind of info in a README update

**Comment by saknopper** [comment]
When I remove `0000_header.conf` the parse error goes away. I didn't modify anything else yet.

**Comment by saknopper** [comment]
I think I've found a potential cause of the issue. When I run

```
cat *.conf > modsecurity_mono.conf
```
And then look at monolithic file, I see this:

```
##########################################################
##########################################################input {

  stdin {
    type => "mod_security"
```
So somehow the first line of `1000_input_stdin_example.conf` is appended to the last line of `0000_header.conf` which is a comment line.

**Comment by saknopper** [comment]
It comes down to `0000_header.conf` not having a newline at the end of the file. But there are several files with the same issue.
