### ISSUE TITLE
Logstash can't start with logstash-modsecurity.conf enabled

### ISSUE THREAD

**Issue by intelbg** [bitsofinfo/logstash-modsecurity#40]
Hi, I moved the file logstash-modsecurity-example.cfg to logstash-modsecurity.conf in /etc/logstash/conf.d/ and then logstash no more start. The error is the following:

Error: Expected one of #, input, filter, output at line 499, column 1 (byte 15172) after  {:level=>:error}

If I disable or move this file it starts. I want to monitor the audit log of nginx, not of apache - this is not the problem why it can't start but it would be great if you tell me that this will not work. Why it can't start?

Also, in the documentation you say "Set the path in logstash-modsecurity.conf to path => "/var/log/httpd/modsec_audit.log"", but I nowhere I found path or where to put this path?

Thank you in advance!

**Comment by bitsofinfo** [comment]
Don't know, please paste the lines of configuration that are running @ ~499 (its a series of includes so you may have to merge them to determine that)
