### ISSUE TITLE
String escaping

### ISSUE THREAD

**Issue by theforcedk** [bitsofinfo/logstash-modsecurity#41]
https://github.com/bitsofinfo/logstash-modsecurity/blob/65f788346ddfd6ae30c8bd4821d5e549625edcde/2110_filter_section_k_parse_matchedRules.conf#L14

Just a comment to try out this new "config.support_escapes" feature; this is supposedly fixed in PR https://github.com/elastic/logstash/pull/7442

**Comment by bitsofinfo** [comment]
Cool - please feel free to contribute a PR when its available in the wild!
