### ISSUE TITLE
Modsecurity3 and Ruby Error

### ISSUE THREAD

**Issue by yuynagforhacker** [bitsofinfo/logstash-modsecurity#45]
Hello, I have a question for Mod_security v3 and Ruby
[ERROR][logstash.filters.ruby    ] Ruby exception occurred: undefined method `/' for nil:NilClass
[ERROR][logstash.filters.ruby    ] Ruby exception occurred: undefined method `/' for nil:NilClass
[ERROR][logstash.filters.ruby    ] Ruby exception occurred: no implicit conversion from nil to integer

Is it because logstash-modsecurity is not compatible with modsecurity v3.0?

my environment is modsecurity3.0+nginx1.15+ELK5

**Comment by yuynagforhacker** [comment]
This problem still occurs when using filebeat to transfer data, but the data will be transmitted in the past, except that the contents of the filter are not transmitted.
I used logstash5.4.0 to transfer the modsecurity2.9 log. I didn't report an error when I first started using it, but I will report this error once I stop logstash re-opening. What is the problem?

**Comment by bitsofinfo** [comment]
Hello - I am not sure as to your specific issue, I don't have a lot of time to maintain this project recently and have not run it with modsec 3. 

If you come up with a solution or workaround please contribute it back in the form of a PR or more information on this ticket so it can benefit others.

**Comment by yuynagforhacker** [comment]
Well, I am using native JSON to pass data all the time, but because of the lack of filter, it is very simple compared with your project. I will use it for a while to learn how to write filter. I have time to study and improve it.

Thanks.

**Comment by yuynagforhacker** [comment]
@bitsofinfo I have a new question
JSON is 
{"transaction":{"client_ip":"x.x.x.x", xxxxxxxxxxx}}
I want to extract the client_ip field to geoip, how should the filter be written?

**Comment by yuynagforhacker** [comment]
> @bitsofinfo I have a new question
> JSON is
> {"transaction":{"client_ip":"x.x.x.x", xxxxxxxxxxx}}
> I want to extract the client_ip field to geoip, how should the filter be written?

My filter conf is
  1 filter {
  2 
  3   grok {
  4      match => { "message" => "%{IPV4:client_ip}"}
  5   }
  6 
  7 
  8 
  9   geoip {
 10       source => "client_ip"
 11       target => "geoip"
 12       add_field => ["[geoip][coordinates]","%{[geoip][longitude]}"]
 13       add_field => ["[geoip][coordinates]","%{[geoip][latitude]}"]
 14   }
 15   mutate {
 16       convert => [ "[geoip][coordinates]", "float"]
 17   }
 18 
 19 }


But there is no new client_ip and geoip is null...

**Comment by yuynagforhacker** [comment]
> > @bitsofinfo I have a new question
> > JSON is
> > {"transaction":{"client_ip":"x.x.x.x", xxxxxxxxxxx}}
> > I want to extract the client_ip field to geoip, how should the filter be written?
> 
> My filter conf is
> 1 filter {
> 2
> 3 grok {
> 4 match => { "message" => "%{IPV4:client_ip}"}
> 5 }
> 6
> 7
> 8
> 9 geoip {
> 10 source => "client_ip"
> 11 target => "geoip"
> 12 add_field => ["[geoip][coordinates]","%{[geoip][longitude]}"]
> 13 add_field => ["[geoip][coordinates]","%{[geoip][latitude]}"]
> 14 }
> 15 mutate {
> 16 convert => [ "[geoip][coordinates]", "float"]
> 17 }
> 18
> 19 }
> 
> But there is no new client_ip and geoip is null.
