### ISSUE TITLE
Some extra setup

### ISSUE THREAD

**Issue by equick** [bitsofinfo/logstash-modsecurity#9]
Hi,

Thanks for making this available. I'm quite new to logstash so struggled a bit when setting this up.
Not sure if everyone will have the same problem but I had to carry out the steps below.
The version I have is logstash-1.4.2-1_2c0f5a1.noarch on Fedora 18.

On the agent host, copy logstash-modsecurity.conf to /etc/logstash/conf.d and logstash_modsecurity_patterns to /etc/logstash/patterns.

In logstash-modsecurity.conf, change

patterns_dir => "./patterns/logstash_modsecurity_patterns"
to:
patterns_dir => "/etc/logstash/patterns/logstash_modsecurity_patterns"

And add the line below to specify the log type as mod_security

input {
  file {
    path => "/var/log/httpd/modsec_audit.log"
    type => "mod_security"
  }
}

Depending on the permissions on modsec_audit.log, you may need to run this also:

setfacl -m u:logstash:r /var/log/httpd/modsec_audit.log

After doing that, restart the logstash agent

Hope this is helpful!
Ed

**Comment by bitsofinfo** [comment]
Cool, please feel free to generalize your instructions/tips, add a section to the README.md about "setup", submit a PR, I'll review and merge so it will just be on the README

**Comment by equick** [comment]
Done :)
